# AULA - 8

## Aprofundamento no NumPy

Neste notebook irá cobrir os tópicos de:
> Indexação

> Fatiamento de arrays


O conteúdo desta apostila é extremamente importante para o curso, não só para Numpy. 

Onde veremos como extrair, do array, os valores que nos são úteis.

In [1]:
import numpy as np

In [2]:
matriz = np.arange(0,50,5)

In [3]:
matriz

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

A extração de valores pode ser feita do mesmo jeito que em listas, utilizando os colchetes e passando o indice dos valores desejados.

In [4]:
matriz[5]

25

In [5]:
matriz[2:6]

array([10, 15, 20, 25])

In [6]:
matriz[:5]

array([ 0,  5, 10, 15, 20])

In [7]:
matriz[5:]

array([25, 30, 35, 40, 45])

As matrizes retiradas podem ser manipuladas também, podendo sofrer alterações.

In [8]:
matriz[5:] / 5

array([5., 6., 7., 8., 9.])

In [9]:
matriz[5:]

array([25, 30, 35, 40, 45])

In [10]:
matriz[5:] =  5

In [11]:
matriz

array([ 0,  5, 10, 15, 20,  5,  5,  5,  5,  5])

Agora, para extrair dados de uma mariz com mais de uma dimensão, tem que ser utilizado mais de um colchetes, sendo assim, o primeiro se refere às linhas da matriz e o segundo às colunas, e assim por diante conforme a matriz vai aumentando de dimensões.

In [12]:
matriz = np.arange(0,50,5).reshape((5,2))

In [13]:
matriz

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

In [14]:
matriz.shape

(5, 2)

In [15]:
matriz[3][:]

array([30, 35])

##### Atenção!
Você pode passar o conteúdo de uma matriz para outra, porém quando a "nova" matriz é alterada, ela altera também a primeira, pois ela cria uma referência para a anterior e não uma completamente nova. Isso ficará mais claro com o exemplo a seguir.

In [16]:
matriz

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

In [17]:
matriz2 = matriz[3][:]

In [18]:
matriz2

array([30, 35])

In [19]:
matriz2[:] = 10

In [20]:
matriz

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [10, 10],
       [40, 45]])

Como pode ver, foi alterado o valor na segunda matriz, porém o valor alterado foi passado para a primeira também, justamente por essa caracteristica. 

E para contornar este problema, podemos usar o método copy(), que com o uso dele o valor não será atribuido, mas sim copiado, e então criando uma variável independente, como o esperado.

In [21]:
matriz2 = matriz[4][:].copy()

In [22]:
matriz2

array([40, 45])

In [23]:
matriz2[:] = 10

In [24]:
matriz

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [10, 10],
       [40, 45]])

Pronto, valor inálterado na primeira matriz.

Agora, outra forma de extrair elementos das matrizes, além de utilizar a notação também usada para listas, é uitilizando um colchete só, e separando os valores desejados por virgula, é uma maneira bem parecida.

In [25]:
matriz3 = np.arange(0,100,5).reshape((10,2))

In [26]:
matriz3

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45],
       [50, 55],
       [60, 65],
       [70, 75],
       [80, 85],
       [90, 95]])

Utilizando, apenas um colchete e separando por virgula, funciona do mesmo jeito, antes da virgula estaria separando as linhas desejadas, e após a virgula, as colunas.

In [27]:
matriz3[1:4,:]

array([[10, 15],
       [20, 25],
       [30, 35]])

In [28]:
matriz3[1:9,:1]

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80]])

Agora veremos que é possível fazer operações lógicas com as matrizes, e utilizar isso para tratar e separar melhor os dados necessários para o programa, ao invés de fatiar apenas por linhas e colunas.

In [29]:
matriz3 < 50

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

No exemplo acima foi pedida para a matriz para retornar verdadeiro ou falso nos elementos dos quais são menores que 50, e isso facilitaria o tratamento de dados onde há uma matriz enorme onde os dados estão fora de ordem.

In [30]:
bol = matriz3 < 50

In [31]:
matriz3[bol]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

Como pode ver, se o valor passado for atribuido a uma variavel do tipo booleano, pode-se separar mais facilmente a matriz.