# AULA - 9

## Aprofundamento no NumPy

Neste notebook será abordado os temas de:
> Operações com arrays

> Funções prontas da biblioteca

In [1]:
import numpy as np

Podemos fazer operações com matrizes, como se fossem variáveis comuns.

In [2]:
matriz = np.arange(0,16)

In [3]:
matriz

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
matriz + matriz

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [5]:
matriz * matriz

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [6]:
matriz / matriz

C:\Users\Coder Factory\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

No exemplo acima houve um erro, porém isso não impediu que o python executasse a linha, o erro dado é um erro apenas matemático, onde não há divisão por zero.

In [7]:
matriz - matriz

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##### Obs:
É importante que as matrizes sejam do mesmo tamanho para que as operações possam ser feitas.

In [8]:
matriz + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

As operações são feitas indice por indice, como pode ser visto em todos os exemplos acima, por isso, é importante que as matrizes sejam do mesmo tamanho para que as operações sejam efetuadas.

### Funçôes matemáticas do NumPy

O NumPy possui por sí só algumas funções prontas para a matemática, desde o básico à algumas avançadas.

Raiz quadrada:

In [9]:
np.sqrt(matriz)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

Exponenciação:

In [10]:
np.exp(matriz)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

Média:

In [11]:
np.mean(matriz)

7.5

Desvio padrão:

In [12]:
np.std(matriz)

4.6097722286464435

Seno:

In [13]:
np.sin(matriz)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

Cosseno:

In [14]:
np.cos(matriz)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791])

Tangente:

In [15]:
np.tan(matriz)

array([ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
        1.15782128e+00, -3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
       -6.79971146e+00, -4.52315659e-01,  6.48360827e-01, -2.25950846e+02,
       -6.35859929e-01,  4.63021133e-01,  7.24460662e+00, -8.55993401e-01])

Maximo:

In [16]:
np.max(matriz)

15

Minimo:

In [17]:
np.min(matriz)

0

Soma:

In [18]:
np.sum(matriz)

120