# AULA - 7 

## Introdução a Numpy

Vamos lá, neste notebook, iremos começar a ver o que faz do python ser o que é, com nossa primeira biblioteca de analize de dados o Numpy. 

Para instalar o Numpy, abra o prompt de comando do anaconda e digite:
> conda install numpy

O Numpy é rapido e eficeiente, utilizado para algebra linear, e será a principal ao longo do curso, pois ela é base para a criação de muitas outras.

Primeiro vamos começar importando a biblioteca para nosso notebook.

In [1]:
import numpy as np

Na linha acima importamos a biblioteca e demos um "apelido" a ela, de "np".

Com o uso do Numpy, criaremos "arrays" que podem ser de 1, 2 ou mais dimensões.

In [2]:
lista = [1, 2, 3, 4]

In [3]:
np.array(lista)

array([1, 2, 3, 4])

In [4]:
matriz2d = [[1,2,3,4],[5,6,7,8]]

In [5]:
np.array(matriz2d)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

As matrizes são de 1 dimensão e 2 dimensões, como pode ver pela quantidade de colchetes, ou de linhas e colunas.

Também existem diversos outros métodos para o numpy, possibilitando a criação de muitos outros tipos de matrizes para usos variados, por exemplo:

Uma matriz padrão, ao invés de digitar todo o conteúdo da matriz caso ela siga um padrão, pode-se usar o método .arange(), onde se passa para o método, por parâmetro, o início, o final e o intervalo.

In [6]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Lembrando que o número final não será incluido.

Pode-se também ser criadas matrizes compostas apenas por zeros, uns, matrizes identidade (usadas na matemática).

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Para criar uma matriz com mais de uma dimensão, tem que ser passada uma tupla por parametro, com a quantidade de elementos igual a quantidade de dimensões necessarias.

In [10]:
np.zeros((5, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((5,3,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

O método .linspace() demonstrado a seguir, cria uma matriz de um número a outro com um a quantidade de números passada no terceiro parâmetro, divididas igualmente. O uso dela ficará mais claro na visualização do exemplo.

In [14]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [15]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Como pode ser visto, há 5 números, divididos igualmente, entre oa 2 primeiros números passados por parâmetro.

#### Métodos .random

Estes métodos geram números randomicos dentro de um intervalo, dependendo do submétodo utilizado.

In [16]:
np.random.rand(5)

array([0.29625571, 0.47905552, 0.29837023, 0.70813501, 0.59355358])

Este submétodo gera números que variam de 0 a 1, positivo apenas.

In [17]:
np.random.randn(5)

array([ 0.99194067, -0.32853458, -0.67850475, -0.51496839,  1.26557047])

Já este submétodo gera números que variam de -1 ate 1.

In [18]:
np.random.randint(0, 100, 10)

array([75, 21, 50, 88, 95, 83, 10, 30, 64, 20])

O submétodo acima gera números inteiros dentro do intervalo estipulado por você.

A seguir veremos mais alguns métodos e atributos do numpy, porém não vamos entrar a fundo no caso dos atributos, pois é assunto para orientação a objeto, que não será focado no curso.

In [19]:
matriz = np.random.rand(25)

In [20]:
matriz

array([0.85173818, 0.1486229 , 0.68372614, 0.93993669, 0.11672547,
       0.2631686 , 0.43235683, 0.90888329, 0.59013552, 0.94674837,
       0.06392318, 0.02570032, 0.94463509, 0.92227446, 0.82710964,
       0.42908673, 0.15952124, 0.78006708, 0.41959573, 0.90153578,
       0.56715368, 0.19592229, 0.36193036, 0.84395745, 0.44993691])

In [24]:
matriz = matriz.reshape((5,5))

In [25]:
matriz

array([[0.85173818, 0.1486229 , 0.68372614, 0.93993669, 0.11672547],
       [0.2631686 , 0.43235683, 0.90888329, 0.59013552, 0.94674837],
       [0.06392318, 0.02570032, 0.94463509, 0.92227446, 0.82710964],
       [0.42908673, 0.15952124, 0.78006708, 0.41959573, 0.90153578],
       [0.56715368, 0.19592229, 0.36193036, 0.84395745, 0.44993691]])

Este método acima, remodela a matriz, no caso, transformou uma matriz de uma dimensão de 25 itens em uma matriz de 5 linhas por 5 colunas.

E para acessar e verificar o tamanho de uma matriz podemos usar um atributo dela. O shape.

In [26]:
matriz.shape

(5, 5)

In [27]:
matriz.max()

0.9467483681094768

In [28]:
matriz.min()

0.02570032418616164

Os dois métodos acima retornam os maiores ou os menores valores da matriz pedida. E com os outros dois a seguir pode-se ver onde estão estes valores na matriz, ou seja, o indice deles.

In [29]:
matriz.argmax()

9

In [31]:
matriz.argmin()

11